<?php

namespace AppCofidurBundle\Repository;

/**
 * OperatorCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
