<?php

namespace AppCofidurBundle\Repository;

/**
 * OperatorTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
