<?php

namespace AppCofidurBundle\Repository;

/**
 * OperatorFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
