<?php

namespace AppCofidurBundle\Repository;

/**
 * OperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorRepository extends \Doctrine\ORM\EntityRepository
{
}
